FROM debian:12-slim

ARG CONTAINER_GID=10000
ARG CONTAINER_UID=10000

ARG MAINTAINER="https://github.com/jsknnr/squad44-server"
ARG IMAGE_VERSION="v1.0.0-devel"

ENV DEBIAN_FRONTEND="noninteractive"
ENV SQUAD44_PATH="/home/steam/squad44"
ENV STEAMCMD_PATH="/home/steam/steamcmd"
ENV STEAM_SDK64_PATH="/home/steam/.steam/sdk64"
ENV STEAM_APP_ID="746200"

ENV SQUAD44_CONFIG_PATH="${SQUAD44_PATH}/PostScriptum/ServerConfig"
ENV GAME_PORT="7787"
ENV QUERY_PORT="27165"
ENV RCON_PORT="21114"
ENV MAX_PLAYERS=80
ENV RESERVED_SLOTS=0
ENV RANDOM_MAP_ROTATION="NONE"
ENV PREVENT_TEAM_CHANGE_IF_UNBALANCED="true"
ENV NUM_PLAYERS_DIFF_FOR_TEAM_CHANGE="3"
ENV MAP_VOTING="false"
ENV SERVER_MESSAGE_INTERVAL=600
ENV TK_AUTOKICK_ENABLED="true"

RUN groupadd -g ${CONTAINER_GID} steam \
    && useradd -g ${CONTAINER_GID} -u ${CONTAINER_UID} -m steam \
    && dpkg --add-architecture i386 \
    && apt-get update \
    && apt-get install -y \
        ca-certificates \
        curl \
        lib32gcc-s1 \
        locales \
        procps \
    && echo 'LANG="en_US.UTF-8"' > /etc/default/locale \
    && echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
    && locale-gen \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean \
    && apt-get autoremove -y

USER steam

COPY entrypoint.sh /home/steam/entrypoint.sh

RUN mkdir -p ${SQUAD44_PATH} \
    && mkdir -p ${STEAMCMD_PATH} \
    && curl -sqL https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz | tar zxvf - -C ${STEAMCMD_PATH} \
    && chmod +x ${STEAMCMD_PATH}/steamcmd.sh \
    && ${STEAMCMD_PATH}/steamcmd.sh +quit \
    && mkdir -p ${STEAM_SDK64_PATH} \
    && cp ${STEAMCMD_PATH}/linux64/steamclient.so ${STEAM_SDK64_PATH}/steamclient.so \
    && echo "${IMAGE_VERSION}" > /home/steam/image_version \
    && echo "${MAINTAINER}" > /home/steam/image_maintainer \
    && echo "${CONTAINER_UID}:${CONTAINER_GID}" > /home/steam/expected_filesystem_permissions
 
WORKDIR /home/steam

CMD ["/home/steam/entrypoint.sh"]
